export const DomainErrorCode = {
  // User Domain
  DOMAIN_VALIDATION_FAILED: "DOMAIN_VALIDATION_FAILED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  PASSWORD_LOGIN_UNAVAILABLE: "PASSWORD_LOGIN_UNAVAILABLE",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_REPLACED: "REFRESH_TOKEN_REPLACED",
  REFRESH_TOKEN_REVOKED: "REFRESH_TOKEN_REVOKED",
  USER_DELETED: "USER_DELETED",
  USER_DISABLED: "USER_DISABLED",

  // Project domain
  PROJECT_ALREADY_ARCHIVED: "PROJECT_ALREADY_ARCHIVED",
  PROJECT_NOT_ACTIVE: "PROJECT_NOT_ACTIVE",
  MEMBERSHIP_NOT_ACTIVE: "MEMBERSHIP_NOT_ACTIVE",
  CANNOT_REMOVE_LAST_WRITER: "CANNOT_REMOVE_LAST_WRITER",
  CANNOT_INVITE_AS_WRITER: "CANNOT_INVITE_AS_WRITER",
  USER_ALREADY_MEMBER: "USER_ALREADY_MEMBER",
  INVITATION_NOT_PENDING: "INVITATION_NOT_PENDING",
  OWNERSHIP_TRANSFER_INVALID: "OWNERSHIP_TRANSFER_INVALID",
} as const;

export type DomainErrorCode =
  (typeof DomainErrorCode)[keyof typeof DomainErrorCode];
