export const DomainErrorCode = {
  DOMAIN_VALIDATION_FAILED: "DOMAIN_VALIDATION_FAILED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  PASSWORD_LOGIN_UNAVAILABLE: "PASSWORD_LOGIN_UNAVAILABLE",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_REPLACED: "REFRESH_TOKEN_REPLACED",
  REFRESH_TOKEN_REVOKED: "REFRESH_TOKEN_REVOKED",
  USER_DELETED: "USER_DELETED",
  USER_DISABLED: "USER_DISABLED",
} as const;

export type DomainErrorCode =
  (typeof DomainErrorCode)[keyof typeof DomainErrorCode];
