import {
  ContentRelationship,
  type ContentRelationshipProperties,
} from "../../domain/support/ContentRelationship.js";

import type {
  ContentRelationship as PrismaContentRelationship,
  Prisma,
} from "../../../../../generated/prisma/client.js";

export const ContentRelationshipMapper = {
  toDomain(row: PrismaContentRelationship): ContentRelationship {
    const props: ContentRelationshipProperties = {
      id: row.id,
      version: row.version,
      projectId: row.projectId,
      sourceEntityType: row.sourceEntityType,
      sourceEntityId: row.sourceEntityId,
      targetEntityType: row.targetEntityType,
      targetEntityId: row.targetEntityId,
      // `relation_type` is a plain TEXT column — no enum, no CHECK
      // (`content-support.prisma:65`, `20260711000100_init_schema`) — so this
      // cast asserts nothing. It is the same move as SceneMapper's
      // Passed through verbatim, and since step 4 nothing downstream narrows it
      // either: the predicate is project data, so a name this codebase has never
      // heard of is a legitimate row. What keeps the column honest is the
      // composite foreign key `(project_id, relation_type) ->
      // relationship_definitions(project_id, predicate)`, which binds every
      // writer rather than only callers who go through the entity.
      relationType: row.relationType,
      sourceAssertionId: row.sourceAssertionId,
      note: row.note,
      createdByUserId: row.createdByUserId,
      createdAt: row.createdAt,
      updatedAt: row.updatedAt,
    };

    return ContentRelationship.reconstitute(props);
  },

  // `id` is absent on purpose and supplied by the repository's create() call,
  // exactly like SceneMapper.toPersistence (`../story/SceneMapper.ts:29-43`):
  // the aggregate owns its id (generated by IdGenerator in the service), and
  // keeping it out of the mapper keeps this shape usable for any create path.
  // `version` is left to the column default (`@default(0)`), which is the same
  // value `create()` puts on the aggregate.
  //
  // BOTH TIMESTAMPS ARE WRITTEN EXPLICITLY, and that is the one place this
  // mapper departs from its Phase 4-6 siblings, which let the database fill
  // them. The departure is forced by Flow 4 step 10
  // (`02-system-design/03_flow_04_content_relationship.md:44`): create RETURNS
  // the new relationship, while every Phase 4-6 create returns only an id
  // (`CharacterService.ts:34-36`). Left to the defaults, one row would carry
  // three different clocks — `created_at` from Postgres
  // (`DEFAULT CURRENT_TIMESTAMP`, `20260711000100_init_schema/migration.sql:364`),
  // `updated_at` from Prisma's `@updatedAt` (the column has no DB default,
  // `:365`), and the response body from the injected Clock — so a client that
  // POSTed and then GETed would see two different `createdAt` values for the
  // same row. Writing the aggregate's own timestamps collapses all three into
  // the one clock the application controls and can test.
  //
  // VERIFIED empirically before relying on it (Prisma 7.8.0 / @prisma/adapter-pg
  // / Postgres, probe 2026-08-15 in the ink-path devcontainer, script removed
  // afterwards): an explicit value on create wins over BOTH `@default(now())`
  // and `@updatedAt` — the row read back with raw SQL carried exactly the two
  // timestamps handed in, not the server's. Without that probe this comment
  // would be an assumption, since `@updatedAt` is normally described as
  // client-managed.
  toPersistence(
    contentRelationship: ContentRelationship,
  ): Prisma.ContentRelationshipUncheckedCreateInput {
    const snapshot = contentRelationship.toSnapshot();

    return {
      projectId: snapshot.projectId,
      createdAt: snapshot.createdAt,
      updatedAt: snapshot.updatedAt,
      sourceEntityType: snapshot.sourceEntityType,
      sourceEntityId: snapshot.sourceEntityId,
      targetEntityType: snapshot.targetEntityType,
      targetEntityId: snapshot.targetEntityId,
      relationType: snapshot.relationType,
      sourceAssertionId: snapshot.sourceAssertionId,
      note: snapshot.note,
      createdByUserId: snapshot.createdByUserId,
    };
  },

  // Only `note` (plus the bookkeeping columns) is written back. Both endpoints
  // and `relation_type` are absent for the same reason SceneMapper omits
  // `chapterId` (`../story/SceneMapper.ts:52-58`): the entity exposes no way to
  // change them — `updateNote()` is the sole mutator — so persisting them could
  // only ever rewrite identical values, or silently enable a re-point the domain
  // never sanctioned. Here that is not merely tidiness: those four columns plus
  // `relation_type` ARE the row's natural identity (the 6-column unique index),
  // and Flow 4 §Update Relation (FROZEN 2026-08-14) rules that changing them is
  // delete + create, never an update.
  //
  // `version: { increment: 1 }` lives here rather than in the entity, matching
  // SceneMapper.toUpdatePersistence: the aggregate must keep the version it was
  // read at, because the adapter needs that value as the guard in
  // `where: { id, version }`.
  toUpdatePersistence(
    contentRelationship: ContentRelationship,
  ): Prisma.ContentRelationshipUncheckedUpdateManyInput {
    const snapshot = contentRelationship.toSnapshot();

    return {
      note: snapshot.note,
      updatedAt: snapshot.updatedAt,
      version: { increment: 1 },
    };
  },
};
