import type { ContentEntityType } from "../../domain/support/ContentRevision.js";

// The write half of the polymorphic content dispatch, and the piece that makes
// decision D8 possible: applying an `attribute_change` assertion has to mutate one
// of nine entity tables, insert its `ContentRevision` and move its
// `current_revision_id` — all inside the SAME transaction that locks the assertion
// row and stamps `applied_at`.
//
// Why not simply call the nine existing content services: each of them opens its
// own `ContentUnitOfWork.transaction()` (`../story/CharacterService.ts`
// persistChange), so `applied_at` could never be atomic with the mutation it
// records. `16:158` requires one transaction; two would leave a window where the
// entity has changed and the assertion still says pending, or the reverse.
//
// The adapter therefore owns three things per entity type — load, set one field,
// persist with a new revision — and this port owns none of them. What stays
// OUTSIDE, in NarrativeTransitionService, is everything that is identical for
// all nine: the row lock, the idempotency re-check, `markApplied()`, and the
// outbox event.
export type AppliedAttributeChange = {
  // Read from the aggregate rather than trusted from the assertion: between
  // declaring an assertion and applying it the target row may have been deleted and
  // its id reused by another project. The service compares and answers 404.
  projectId: string;

  // `oldVersion + 1`, the same derivation every Phase 4-6 service uses
  // (`03-database-design/10_content_revisions_vector_indexing.md:128`). Carried
  // out so the outbox payload can name it without a second read.
  revisionNumber: number;

  // False when the entity already holds the intended value. Nothing is written
  // in that case — no revision, no version bump — and the service turns it into
  // a 409 (decision D5, extended to attribute changes at 7.7): the world already
  // matches the intent, so marking the assertion applied would claim this
  // transition caused a state it found. The writer's escape hatch is the same as
  // for the other two drift cases — delete the pending assertion.
  changed: boolean;
};

export type ApplyAttributeChangeInput = {
  entityType: ContentEntityType;
  entityId: string;

  // The DOMAIN property name, already resolved from the stored wire name by
  // `domainAttributeFieldOf()`. This port never sees a `field_path`: resolving
  // it is the allowlist's job, and re-doing the lookup here would be a second
  // place for the two names to disagree.
  domainField: string;

  newValue: string;

  // Generated by the caller, before this call, because the caller also has to
  // stamp it onto the assertion (`content_revision_id`) after the write succeeds.
  // Handing the id down rather than returning it keeps the two writes from
  // needing a second round-trip to agree on one value.
  revisionId: string;

  changedByUserId: string;
  now: Date;
};

export type ContentAttributeMutator = {
  // `null` means the target row does not exist — the service answers 404, the
  // same shape `ContentEntityLocator.locate()` uses for the declare path.
  //
  // NOT PROJECT-SCOPED, and the caller must know it: the implementation loads
  // the target by id alone and reports the `projectId` it found, leaving the
  // comparison to the service. So a cross-tenant id reaches the WRITE before it
  // is rejected — the write is rolled back with the transaction and nothing
  // leaks, but what keeps it out of reach in practice is the locator check the
  // service performs before opening the transaction, not this port. Same
  // 404-not-403 rule applies once the comparison happens.
  applyAttributeChange(
    input: ApplyAttributeChangeInput,
  ): Promise<AppliedAttributeChange | null>;
};
