import {
  Character,
  type CharacterProperties,
} from "../../domain/story/Character.js";

import type {
  Character as PrismaCharacter,
  Prisma,
} from "../../../../../generated/prisma/client.js";

export const CharacterMapper = {
  toDomain(row: PrismaCharacter): Character {
    const props: CharacterProperties = {
      id: row.id,
      version: row.version,
      projectId: row.projectId,
      createdByUserId: row.createdByUserId,
      name: row.name,
      archetype: row.archetype,
      background: row.background,
      personality: row.personality,
      goal: row.goal,
      description: row.description,
      content: row.content,
      status: row.status,
      currentRevisionId: row.currentRevisionId ?? "", // Force Entity validation if a required DB value is unexpectedly null.
      createdAt: row.createdAt,
      updatedAt: row.updatedAt,
    };

    return Character.reconstitute(props);
  },

  toPersistence(character: Character): Prisma.CharacterUncheckedCreateInput {
    const snapshot = character.toSnapshot();

    return {
      projectId: snapshot.projectId,
      createdByUserId: snapshot.createdByUserId,
      name: snapshot.name,
      archetype: snapshot.archetype,
      personality: snapshot.personality,
      background: snapshot.background,
      goal: snapshot.goal,
      description: snapshot.description,
      content: snapshot.content,
      status: snapshot.status,
      currentRevisionId: snapshot.currentRevisionId,
    };
  },

  toCreatePersistence(
    character: Character,
  ): Prisma.CharacterUncheckedCreateInput {
    return {
      ...this.toPersistence(character),
      // The in-memory entity already carries the revisionId it will link to
      // (pre-generated by the Service so the domain object is always valid),
      // but the physical row must not have it yet — see linkRevision() on
      // CharacterRepository for why.
      currentRevisionId: null,
    };
  },

  toUpdatePersistence(
    character: Character,
  ): Prisma.CharacterUncheckedUpdateManyInput {
    const snapshot = character.toSnapshot();

    return {
      name: snapshot.name,
      archetype: snapshot.archetype,
      personality: snapshot.personality,
      background: snapshot.background,
      goal: snapshot.goal,
      description: snapshot.description,
      content: snapshot.content,
      status: snapshot.status,
      currentRevisionId: snapshot.currentRevisionId,
      updatedAt: snapshot.updatedAt,
      version: { increment: 1 },
    };
  },
};
